apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim
  namespace: keycloak
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi