FROM maven:3.9.6-eclipse-temurin-17-alpine AS builder
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Étape 2 : Image exécutable avec OpenJDK
#FROM openjdk:17-alpine
FROM selenium/standalone-chrome:latest
USER root
RUN apt-get update && apt-get install -y openjdk-17-jdk && apt-get clean
WORKDIR /dev
COPY --from=builder /build/target/chatintell-0.0.1-SNAPSHOT.jar /usr/local/lib/dev.jar
COPY keycloakk.crt /tmp/keycloakk.crt
RUN keytool -importcert -alias keycloak-selfsigned \
    -file /tmp/keycloakk.crt \
    -cacerts -storepass changeit -noprompt

    
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/usr/local/lib/dev.jar"]
