FROM maven:3.9.6-eclipse-temurin-17-alpine AS builder
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Étape 2 : Image exécutable avec OpenJDK
FROM openjdk:17-alpine
WORKDIR /dev
COPY --from=builder /build/target/chatintell-0.0.1-SNAPSHOT.jar /usr/local/lib/dev.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/usr/local/lib/dev.jar"]
