# -------- Stage 1: Build Angular Application --------
    FROM node:18-alpine AS build

    # Set working directory
    WORKDIR /app
    
    # Copy and install dependencies
    COPY package*.json ./
    RUN npm install -g @angular/cli && npm install --force
    
    # Clean old builds and npm cache (optional, safe cleanup)
    RUN rm -rf dist/ && npm cache clean --force
    
    # Copy the entire project
    COPY . .
    
    # Build Angular app with production config
    ARG configuration=production
    RUN npm run build -- --configuration=$configuration --output-path=dist/devo-front
    
    # Optional: verify contents
    RUN ls -la dist/devo-front
    
    # -------- Stage 2: Serve with Nginx --------
    FROM nginx:1.25-alpine
    
    # Remove default nginx web files
    RUN rm -rf /usr/share/nginx/html/*
    
    # Copy compiled Angular app to Nginx path
    COPY --from=build /app/dist/devo-front/browser/ /usr/share/nginx/html
    COPY nginx.crt /etc/nginx/ssl/nginx.crt
    COPY nginx.key /etc/nginx/ssl/nginx.key
    # Copy custom nginx config (optional if you have routes or proxy)
    COPY nginx-custom.conf /etc/nginx/conf.d/default.conf
    
    # Expose HTTP port
    EXPOSE 80
    
    # Start Nginx
    CMD ["nginx", "-g", "daemon off;"]
    