apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: front
spec:
  selector:
    app: front
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort:  80
    - name: https
      protocol: TCP
      port: 443
      targetPort:  443
  type: LoadBalancer   
  
